version: '3.5'

services:
  nginx:
    image: nginx
    restart: always
    depends_on:
      - shinystudio
    volumes:
      - './configs/${SITEPORT}/nginx.conf:/etc/nginx/nginx.conf:z'
      - './configs/${SITEPORT}/certs:/etc/ssl/certs:z'
    ports:
      - ${SITEPORT}:80
      - ${HTTPSPORT}:${HTTPSPORT}

  shinystudio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - influxdb
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './configs/${SITEPORT}/img:/opt/shinyproxy/templates/grid-layout/assets/img:z'
      - "./configs/${SITEPORT}/application.yml:/opt/shinyproxy/application.yml:z"
    environment:
      - APPLICATION_LOGS_TO_STDOUT=false
      - SITEPORT=$SITEPORT
      - CONTENTPATH=$CONTENTPATH
      - USER=$USER
      - USERID=$USERID

  influxdb:
    image: influxdb
    restart: always
    volumes:
      - 'influxdb_data:/var/lib/influxdb'
    environment:
      - INFLUXDB_DB=shinyproxy_usagestats
      - INFLUXDB_REPORTING_DISABLED=true

volumes:
  influxdb_data:

